# extra_scripts/load_env.py
# PlatformIO pre-build script: reads .env and generates src/config.h
# Runs automatically before every build.

import os
import sys

Import("env")


def generate_config(env_obj):
    project_dir = env_obj.subst("$PROJECT_DIR")
    env_file = os.path.join(project_dir, ".env")
    config_h = os.path.join(project_dir, "src", "config.h")

    if not os.path.isfile(env_file):
        print("")
        print("=" * 60)
        print("  ERROR: .env file not found!")
        print("  Please create a .env file in the project root.")
        print("  Copy .env.example and fill in your real credentials:")
        print("")
        print("    cp .env.example .env")
        print("")
        print("  Then edit .env with your actual values.")
        print("=" * 60)
        print("")
        sys.exit(1)

    # Parse .env: skip blank lines and comments
    values = {}
    with open(env_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip()
            # Strip surrounding quotes if present
            if len(val) >= 2 and val[0] in ('"', "'") and val[0] == val[-1]:
                val = val[1:-1]
            values[key] = val

    required_keys = [
        "WIFI_SSID",
        "WIFI_PASS",
        "API_TOKEN",
        "MONKEY_ID",
        "DUCK_TOKEN",
        "DUCK_DOMAIN",
        "ACCESS_PIN",
        "ARDUINO_IP",
        "GATEWAY_IP",
        "SUBNET_MASK",
        "DNS_IP",
    ]

    missing = [k for k in required_keys if k not in values]
    if missing:
        print("")
        print("=" * 60)
        print("  ERROR: Missing keys in .env:")
        for k in missing:
            print("    - " + k)
        print("  Check .env.example for the full list of required keys.")
        print("=" * 60)
        print("")
        sys.exit(1)

    def ip_to_args(ip_str):
        return ", ".join(ip_str.strip().split("."))

    lines = [
        "// config.h - AUTO-GENERATED by extra_scripts/load_env.py",
        "// DO NOT EDIT THIS FILE MANUALLY.",
        "// Edit .env and rebuild instead.",
        "// This file is gitignored and regenerated on every build.",
        "",
        "#pragma once",
        "",
        "// WiFi credentials",
        '#define WIFI_SSID     "{}"'.format(values["WIFI_SSID"]),
        '#define WIFI_PASS     "{}"'.format(values["WIFI_PASS"]),
        "",
        "// VoiceMonkey API",
        '#define API_TOKEN     "{}"'.format(values["API_TOKEN"]),
        '#define MONKEY_ID     "{}"'.format(values["MONKEY_ID"]),
        "",
        "// DuckDNS",
        '#define DUCK_TOKEN    "{}"'.format(values["DUCK_TOKEN"]),
        '#define DUCK_DOMAIN   "{}"'.format(values["DUCK_DOMAIN"]),
        "",
        "// Web interface PIN",
        '#define ACCESS_PIN    "{}"'.format(values["ACCESS_PIN"]),
        "",
        "// Static IP configuration (comma-separated octets for IPAddress constructor)",
        "#define ARDUINO_IP_ARGS  {}".format(ip_to_args(values["ARDUINO_IP"])),
        "#define GATEWAY_IP_ARGS  {}".format(ip_to_args(values["GATEWAY_IP"])),
        "#define SUBNET_ARGS      {}".format(ip_to_args(values["SUBNET_MASK"])),
        "#define DNS_IP_ARGS      {}".format(ip_to_args(values["DNS_IP"])),
    ]

    with open(config_h, "w") as f:
        f.write("\n".join(lines) + "\n")

    print("  [load_env.py] config.h generated successfully from .env")


generate_config(env)
